name: C/C++ CI

on: [push]

jobs:
  build:
    name: C/C++ CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: make test
      run:  make test -C 3_Implementation
